### PR TITLE
New Logo Design for Booktype

### PR DESCRIPTION
**Pull request by ihtiht**
Hi, The booktype is quite handy and I love it. I wanted to design a logo for Booktype. I designed a unique and simple logo. I hope you like it too.

booktype

booktype2

I may have done the PR process wrong. If there is something you do not like or want to add to the logo, please tell me.  If you like, I can give all the necessary logo files in the format you want.

### CODE REVIEW

**Comment by Booktypo** [comment]
Hi,

Thank you very much for your nice logo design! It is great someone puts time and brain into it. 
We launched our actual logo last year together with our Omnibook logo and are very happy with it: the new appearance was well accepted in the market and at the moment we don't see any necessity to change it (again). If we consider a new logo we would be happy to contact you. 
Thanks again. 

Cheers!
Julian

**Comment by danielhjames** [comment]
Hi @ihtiht I like your logo concept! As @Booktypo says, we will probably not change the main logo at the moment, but I think we could work it into the favicon. I'll take a look at that.

**Comment by danielhjames** [comment]
Hi @ihtiht I have used your logo design on https://www.facebook.com/Booktype/ https://twitter.com/booktypo and https://github.com/Booktypo in our colours of orange and black. I will upload a version for the favicon. Thanks!

**Comment by danielhjames** [comment]
Hi @ihtiht if you would like to be credited for the design with your real name in AUTHORS.txt please let me know what that is.

**Comment by danielhjames** [comment]
I have opened https://github.com/booktype/Booktype/pull/867 to commit the favicon design by @ihtiht which is very cool :-)

**Comment by ihtiht** [comment]
I am happy to have contributed to the Booktype even if it is small. Please do not hesitate to contact me for any necessary design changes. You can add me as "Ibrahim Tenekeci"

**Comment by danielhjames** [comment]
Hi @ihtiht please download our contributor agreement from https://github.com/booktype/contributor-agreements/raw/master/individual-contributor-license-agreement.pdf and return it to us at the email address on the document: contact@booktype.pro

A scan or digital photo of the page showing your signature and other details is fine. This allows us to use your design and include it in future Booktype releases. Thanks again!

**Comment by danielhjames** [comment]
I have added your real name in https://github.com/booktype/Booktype/commit/64c2197f34987e9f817b5db051aa7dde62b97989

**Comment by ihtiht** [comment]
Okay. I did.

**Comment by danielhjames** [comment]
Thanks for returning the contributor agreement @ihtiht! You can see your logo design in the favicon of our dev site http://booktype-dev.sourcefabric.org/ which I think is a big improvement.

If you can read Turkish, you might like to contribute to our interface translation in progress: https://www.transifex.com/sourcefabric/booktype/language/tr/
I will send you an email invitation to this Transifex project.

**Comment by ihtiht** [comment]
Thank you for your invitation. I'm a little busy these days. I can also make translation contributions at the first opportunity.

**Comment by danielhjames** [comment]
Cool, thanks again @ihtiht !

**Comment by danielhjames** [comment]
Hi @ihtiht I have added your design to the homepage in this graphic: https://booktype.pro/get_img?ImageId=4180

**Comment by ihtiht** [comment]
Nice ! I was so happy to see that.

**Pull request closed without merging**
