### PR TITLE
BK-2319 Registering multiple usernames with the same email address is possible

### PR DESCRIPTION
**Pull request by ride90**
It's temporary solution. 
We definitely must rewrite entire register part, right now the logic is weird 👎

### CODE REVIEW

**Comment by eos87** [comment]
I agree about reworking the registration part, we should extend default django registration which works pretty well.

**Comment by ride90** [comment]
Hi @eos87 , I've pushed messages, but this files were also edited by localiser, so it produces giant conflict. It is not a big deal to make new messages in a separate commit and push it later. Please, merge it. 🍺

**Comment by danielhjames** [comment]
I can help merge the messages file.

**Comment by ride90** [comment]
Thanks @danielhjames . @eos87 now you can hit merge button.

**Pull request merged**
